sudo: false
language: ruby
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
branches:
  only:
    - master
    - travis

before_install:
  - rvm use @global
  - gem uninstall bundler -x || gem uninstall bundler -a || true
  - gem install bundler -v 1.17.3
  - bundler --version
