sudo: false
language: ruby
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
branches:
  only:
    - master
    - travis

before_install: gem install bundler -v 1.16.2
